/**
 * Compliance-report PDF download.
 *
 * Streams the canonical PDF generated by the backend
 * (`GET /api/v1/apps/loan-onboarding/packages/{id}/compliance/report.pdf`)
 * — the same fpdf2 renderer used by every other report in the platform —
 * and saves it to disk as an actual file download.
 *
 * The previous in-browser HTML-to-print approach was replaced because
 *   1. Calling `window.print()` opens a print dialog instead of producing
 *      a real .pdf file the user can save with one click.
 *   2. Brand consistency: the backend renderer embeds the Logikality logo
 *      and uses the same typography as the TI / TSA reports.
 */
import { fetchCompliancePdfBlob } from "./api";
import type { ComplianceReport } from "./compliance";

/** Sanitise a candidate filename — strip path separators, collapse spaces. */
function _safeFilename(stem: string): string {
  return (
    stem
      .replace(/[/\\?%*:|"<>]/g, "")
      .replace(/\s+/g, "-")
      .slice(0, 80) || "compliance-report"
  );
}

/**
 * Fetch the PDF for `report.packageId` from the backend and trigger a
 * browser download. Caller passes `orgId` (typically from `useOrg()`)
 * because the API client requires it on every tenant-scoped route.
 */
export async function downloadCompliancePdf(
  report: ComplianceReport,
  orgId: string
): Promise<void> {
  if (!orgId) {
    throw new Error("No active organization — cannot download report.");
  }
  const blob = await fetchCompliancePdfBlob(orgId, report.packageId);
  const filename = `${_safeFilename(
    report.loanReference || report.packageName || "compliance-report"
  )}.pdf`;
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  // Some browsers (notably Firefox) ignore programmatic clicks on detached
  // anchors, so we attach to the DOM, click, then clean up.
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  // Revoke after the click is queued — immediate revoke races the download
  // in Safari.
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}
