"""add title search and abstracting tables

Revision ID: 9e02cf074b30
Revises: b2c3d4e5f6g7
Create Date: 2026-03-23 20:18:15.046566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID, JSONB


# revision identifiers, used by Alembic.
revision: str = '9e02cf074b30'
down_revision: Union[str, None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ta_county_sources',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('availability', sa.String(length=20), nullable=False),
    sa.Column('portal_url', sa.Text(), nullable=True),
    sa.Column('portal_type', sa.String(length=20), nullable=True),
    sa.Column('search_config', JSONB(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_verified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('county', 'state_code', 'source_type', name='uq_county_source')
    )
    op.create_table('ta_orders',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('created_by', UUID(as_uuid=True), nullable=False),
    sa.Column('property_address', sa.Text(), nullable=False),
    sa.Column('parcel_number', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('legal_description', sa.Text(), nullable=True),
    sa.Column('search_scope', sa.String(length=20), nullable=False),
    sa.Column('search_years', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('pipeline_stage', sa.String(length=50), nullable=True),
    sa.Column('pipeline_error', sa.Text(), nullable=True),
    sa.Column('linked_pack_id', UUID(as_uuid=True), nullable=True),
    sa.Column('org_id', UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['linked_pack_id'], ['ti_packs.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ta_orders_org_id'), 'ta_orders', ['org_id'], unique=False)
    op.create_table('ta_packages',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('order_id', UUID(as_uuid=True), nullable=False),
    sa.Column('package_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('search_scope', sa.String(length=20), nullable=True),
    sa.Column('years_covered', sa.Integer(), nullable=True),
    sa.Column('total_documents', sa.Integer(), nullable=True),
    sa.Column('chain_complete', sa.Boolean(), nullable=False),
    sa.Column('open_flags_count', sa.Integer(), nullable=True),
    sa.Column('property_summary', JSONB(), nullable=True),
    sa.Column('storage_path_pdf', sa.Text(), nullable=True),
    sa.Column('storage_path_json', sa.Text(), nullable=True),
    sa.Column('issued_by', sa.String(length=20), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issuer_id', UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['ta_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('package_number')
    )
    op.create_index(op.f('ix_ta_packages_org_id'), 'ta_packages', ['org_id'], unique=False)
    op.create_table('ta_pipeline_runs',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('order_id', UUID(as_uuid=True), nullable=False),
    sa.Column('input_file_hash', sa.String(length=64), nullable=True),
    sa.Column('ai_platform', sa.String(length=50), nullable=False),
    sa.Column('ai_model', sa.String(length=100), nullable=False),
    sa.Column('parser_prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('chain_prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('anomaly_prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('parser_tool_hash', sa.String(length=64), nullable=False),
    sa.Column('chain_tool_hash', sa.String(length=64), nullable=False),
    sa.Column('anomaly_tool_hash', sa.String(length=64), nullable=False),
    sa.Column('rules_version', sa.String(length=50), nullable=False),
    sa.Column('pipeline_backend', sa.String(length=50), nullable=False),
    sa.Column('version_metadata', JSONB(), nullable=True),
    sa.Column('confidence_summary', JSONB(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('org_id', UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['ta_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ta_pipeline_runs_org_id'), 'ta_pipeline_runs', ['org_id'], unique=False)
    op.create_table('ta_source_assignments',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('order_id', UUID(as_uuid=True), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('availability', sa.String(length=20), nullable=False),
    sa.Column('portal_config_id', UUID(as_uuid=True), nullable=True),
    sa.Column('assigned_to', UUID(as_uuid=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('org_id', UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['ta_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['portal_config_id'], ['ta_county_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ta_source_assignments_org_id'), 'ta_source_assignments', ['org_id'], unique=False)
    op.create_table('ta_raw_documents',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('order_id', UUID(as_uuid=True), nullable=False),
    sa.Column('source_assignment_id', UUID(as_uuid=True), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('document_ref', sa.String(length=255), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('content_format', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['ta_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_assignment_id'], ['ta_source_assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ta_raw_documents_org_id'), 'ta_raw_documents', ['org_id'], unique=False)
    op.create_table('ta_documents',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('order_id', UUID(as_uuid=True), nullable=False),
    sa.Column('raw_document_id', UUID(as_uuid=True), nullable=True),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('recording_date', sa.String(length=20), nullable=True),
    sa.Column('recording_ref', sa.String(length=255), nullable=True),
    sa.Column('legal_description', sa.Text(), nullable=True),
    sa.Column('consideration', sa.Float(), nullable=True),
    sa.Column('grantor', JSONB(), nullable=True),
    sa.Column('grantee', JSONB(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['ta_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['raw_document_id'], ['ta_raw_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ta_documents_org_id'), 'ta_documents', ['org_id'], unique=False)
    op.create_table('ta_chain_links',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('order_id', UUID(as_uuid=True), nullable=False),
    sa.Column('document_id', UUID(as_uuid=True), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(length=20), nullable=False),
    sa.Column('from_party', JSONB(), nullable=True),
    sa.Column('to_party', JSONB(), nullable=True),
    sa.Column('effective_date', sa.String(length=20), nullable=True),
    sa.Column('is_gap', sa.Boolean(), nullable=False),
    sa.Column('gap_description', sa.Text(), nullable=True),
    sa.Column('org_id', UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['ta_documents.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['ta_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ta_chain_links_org_id'), 'ta_chain_links', ['org_id'], unique=False)
    op.create_table('ta_flags',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('order_id', UUID(as_uuid=True), nullable=False),
    sa.Column('document_id', UUID(as_uuid=True), nullable=True),
    sa.Column('chain_link_id', UUID(as_uuid=True), nullable=True),
    sa.Column('flag_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('evidence_refs', JSONB(), nullable=False),
    sa.Column('auto_resolved', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['chain_link_id'], ['ta_chain_links.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['ta_documents.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['ta_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ta_flags_org_id'), 'ta_flags', ['org_id'], unique=False)
    op.create_table('ta_reviews',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('order_id', UUID(as_uuid=True), nullable=False),
    sa.Column('flag_id', UUID(as_uuid=True), nullable=True),
    sa.Column('document_id', UUID(as_uuid=True), nullable=True),
    sa.Column('reviewer_id', UUID(as_uuid=True), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('original_value', JSONB(), nullable=True),
    sa.Column('corrected_value', JSONB(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['ta_documents.id'], ),
    sa.ForeignKeyConstraint(['flag_id'], ['ta_flags.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['ta_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ta_reviews_org_id'), 'ta_reviews', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ta_reviews_org_id'), table_name='ta_reviews')
    op.drop_table('ta_reviews')
    op.drop_index(op.f('ix_ta_flags_org_id'), table_name='ta_flags')
    op.drop_table('ta_flags')
    op.drop_index(op.f('ix_ta_chain_links_org_id'), table_name='ta_chain_links')
    op.drop_table('ta_chain_links')
    op.drop_index(op.f('ix_ta_documents_org_id'), table_name='ta_documents')
    op.drop_table('ta_documents')
    op.drop_index(op.f('ix_ta_raw_documents_org_id'), table_name='ta_raw_documents')
    op.drop_table('ta_raw_documents')
    op.drop_index(op.f('ix_ta_source_assignments_org_id'), table_name='ta_source_assignments')
    op.drop_table('ta_source_assignments')
    op.drop_index(op.f('ix_ta_pipeline_runs_org_id'), table_name='ta_pipeline_runs')
    op.drop_table('ta_pipeline_runs')
    op.drop_index(op.f('ix_ta_packages_org_id'), table_name='ta_packages')
    op.drop_table('ta_packages')
    op.drop_index(op.f('ix_ta_orders_org_id'), table_name='ta_orders')
    op.drop_table('ta_orders')
    op.drop_table('ta_county_sources')
    # ### end Alembic commands ###
